Repository APPSCHOOL2-Android/FinalProject-ShoppingMallService-team4, pull requests merged in 2023-09, with the labels that each got.

#84 Design: 배송 관리/ 조회 UI #60
  agijagi/app/build.gradle
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/OrderManagementDetailFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/OrderManagementFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/adapter/OrderManagementAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/model/OrderManagementModel.kt
  agijagi/app/src/main/res/layout/fragment_custom_option.xml
  agijagi/app/src/main/res/layout/fragment_order_management.xml
  agijagi/app/src/main/res/layout/fragment_order_management_detail.xml
  agijagi/app/src/main/res/layout/item_order_management.xml
  agijagi/app/src/main/res/values/colors.xml
Labels: Design

#90 Design: 내 정보 화면 #85
  agijagi/app/src/main/res/layout/fragment_buyer_mypage.xml
  agijagi/app/src/main/res/menu/menu_buyer_my_page.xml
Labels: Design

#93 Feat: 검색어 입력 중 화면 처리, 최근 검색어 저장 기능 구현 #52
  agijagi/app/src/main/java/likelion/project/agijagi/search/SearchFragment.kt
  agijagi/app/src/main/res/layout/fragment_search.xml
Labels: Feat

#94 Design: 판매상품리스트 UI #81
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/adapter/ProductListAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/model/ProductListModel.kt
  agijagi/app/src/main/res/drawable/box_add_24px.xml
  agijagi/app/src/main/res/layout/fragment_product_list.xml
  agijagi/app/src/main/res/layout/item_product_list.xml
  agijagi/app/src/main/res/layout/item_product_list_dropdown.xml
  agijagi/app/src/main/res/menu/menu_product_list.xml
  agijagi/app/src/main/res/values/array.xml
Labels: Design

#96 feat: 판매자 상품 수정화면 기본 기능 구현 #67
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductAddFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductUpdateFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductUpdateModel.kt
Labels: Feat

#98 Design: 배치 수정 #97
  agijagi/app/src/main/res/layout/fragment_product_add.xml
  agijagi/app/src/main/res/layout/fragment_product_update.xml
Labels: Design

#99 Design: 내 정보 수정 화면 #86
  agijagi/app/src/main/res/layout/fragment_profile_management.xml
Labels: Design

#101 Design: 배송조회 UI 수정 #95
  agijagi/app/src/main/java/likelion/project/agijagi/deliverytracking/DeliveryTrackingFragment.kt
  agijagi/app/src/main/res/layout/fragment_delivery_tracking.xml
Labels: Design

#103 Feat: 구매자, 판매자 화면 전환 #91
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/BuyerMypageFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/ShippingAddFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/ShippingManagementFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/category/CategoryDetailInfoListAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/category/CategoryDetailInfoListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/deliverytracking/DeliveryTrackingFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/order/OrderAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/order/OrderFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/productoption/CustomOptionFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/productoption/ReadyMadeOptionFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/purchase/PaymentFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/OrderManagementDetailFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/SellerMypageFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/SellerNotificationSettingFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/adapter/ProductListAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/shopping/ShoppingListAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/wishlist/WishListAdapter.kt
  agijagi/app/src/main/res/layout/fragment_buyer_mypage.xml
  agijagi/app/src/main/res/layout/fragment_custom_option.xml
  agijagi/app/src/main/res/layout/fragment_delivery_tracking.xml
  agijagi/app/src/main/res/layout/fragment_ready_made_option.xml
  agijagi/app/src/main/res/layout/fragment_seller_notification_setting.xml
  agijagi/app/src/main/res/menu/menu_buyer_my_page.xml
  agijagi/app/src/main/res/menu/menu_seller_my_page.xml
  agijagi/app/src/main/res/navigation/navigation_graph.xml
Labels: Feat

#104 Design: 구매자 알림 설정 #87
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/BuyerNotificationSettingFragment.kt
  agijagi/app/src/main/res/color/switch_toggle_color.xml
  agijagi/app/src/main/res/color/switch_toggle_track_color.xml
  agijagi/app/src/main/res/layout/fragment_alarm.xml
  agijagi/app/src/main/res/layout/fragment_buyer_notification_setting.xml
  agijagi/app/src/main/res/navigation/navigation_graph.xml
Labels: Design

#105 Feat: 상품 등록, 수정 화면 전환 추가 #91
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductAddFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductUpdateFragment.kt
  agijagi/app/src/main/res/navigation/navigation_graph.xml
Labels: Feat

#107 Fix: navigation graph action typo #106
  agijagi/app/src/main/res/navigation/navigation_graph.xml
Labels: Fix

#115 Design: 알림 리스트 화면 UI #100
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/BuyerMypageFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/notification/NotificationFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/notification/NotificationListAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/notification/NotificationListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/notification/NotificationListModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/SellerMypageFragment.kt
  agijagi/app/src/main/res/drawable/new_mark.xml
  agijagi/app/src/main/res/layout/fragment_notification.xml
  agijagi/app/src/main/res/layout/fragment_notification_list.xml
  agijagi/app/src/main/res/layout/item_notification_list.xml
  agijagi/app/src/main/res/menu/menu_notification_list.xml
  agijagi/app/src/main/res/navigation/navigation_graph.xml
Labels: Design

#117 Design: 판매자 알람 설정 화면 UI #116
  agijagi/app/src/main/res/layout/fragment_seller_notification_setting.xml
Labels: Design

#118 Design: CustomOptionFragment #106
  agijagi/app/src/main/java/likelion/project/agijagi/productoption/CustomOptionFragment.kt
  agijagi/app/src/main/res/drawable/back_side.png
  agijagi/app/src/main/res/drawable/back_side_no_stroke.png
  agijagi/app/src/main/res/drawable/front_side.png
  agijagi/app/src/main/res/drawable/front_side_no_stroke.png
  agijagi/app/src/main/res/drawable/left_side.png
  agijagi/app/src/main/res/drawable/left_side_no_stroke.png
  agijagi/app/src/main/res/drawable/right_side.png
  agijagi/app/src/main/res/drawable/right_side_no_stroke.png
  agijagi/app/src/main/res/layout/fragment_custom_option.xml
  agijagi/app/src/main/res/layout/item_custom_option.xml
  agijagi/app/src/main/res/layout/item_custom_option_back.xml
  agijagi/app/src/main/res/layout/item_custom_option_front.xml
  agijagi/app/src/main/res/layout/item_custom_option_left.xml
  agijagi/app/src/main/res/layout/item_custom_option_right.xml
  agijagi/app/src/main/res/values/array.xml
Labels: Design

#122 Design: hint 설정 변경 #119
  agijagi/app/src/main/res/layout/fragment_product_add.xml
  agijagi/app/src/main/res/layout/fragment_product_update.xml
Labels: Design

#123 Fix: profileManagement ID 수정 #120
  agijagi/app/src/main/res/layout/fragment_profile_management.xml
Labels: Fix

#124 Design: 스토어관리 UI #111
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/StoreManagementFragment.kt
  agijagi/app/src/main/res/layout/fragment_store_management.xml
Labels: Design

#128 Design: buyer mypage navigation icon 삭제 #126
  agijagi/app/src/main/res/layout/fragment_buyer_mypage.xml
Labels: Design

#129 Fix: profileManagement 스크롤 뷰 수정 #127
  agijagi/app/src/main/res/layout/fragment_profile_management.xml
Labels: Design

#130 Rename: userchat 폴더, 파일명 수정 #125
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/BuyerMypageFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/chatting/ChattingListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/chatting/ChattingRoomFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/order/OrderAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/product/CustomProductDetailFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/SellerMypageFragment.kt
  agijagi/app/src/main/res/layout/fragment_chatting_list.xml
  agijagi/app/src/main/res/layout/fragment_chatting_room.xml
  agijagi/app/src/main/res/navigation/navigation_graph.xml
Labels: Rename

#131 Design: chatting list ui 구현 #112
  agijagi/app/src/main/java/likelion/project/agijagi/chatting/ChattingListAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/chatting/ChattingListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/chatting/ChattingListModel.kt
  agijagi/app/src/main/res/layout/fragment_chatting_list.xml
  agijagi/app/src/main/res/layout/item_chatting_list.xml
Labels: Design

#132 Design: chatting room 임시 ui 구현 #108
  agijagi/app/src/main/res/drawable/arrow_circle_right_24px.xml
  agijagi/app/src/main/res/drawable/chatting_input_box.xml
  agijagi/app/src/main/res/drawable/chatting_message_box.xml
  agijagi/app/src/main/res/drawable/image_24px.xml
  agijagi/app/src/main/res/layout/fragment_chatting_room.xml
Labels: Design

#136 Feat: 내 프로필 관리, 내 스토어 관리 화면 전환 #91
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/ProfileManagementFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/ShippingUpdateFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/adapter/ShippingManagementAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/StoreManagementFragment.kt
  agijagi/app/src/main/res/navigation/navigation_graph.xml
Labels: Feat

#137 Refactor: 상품 등록, 수정 화면 코드 리펙토링 #134
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductAddFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductAddModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductUpdateFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductUpdateModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/model/ProductAddModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/model/ProductUpdateModel.kt
Labels: Refactor

#140 Feat: buyer_seller_signup_login #62
  agijagi/app/build.gradle
  agijagi/app/src/main/AndroidManifest.xml
  agijagi/app/src/main/java/likelion/project/agijagi/MainActivity.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/BuyerMypageFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/login/LoginFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/SellerMypageFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/JoinDataVo.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/SignupBuyerFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/SignupFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/SignupGoogleBuyerFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/SignupGoogleSellerFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/SignupSelectFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/SignupSellerFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/wishlist/WishListFragment.kt
  agijagi/app/src/main/res/drawable/outline_person_outline_24_nomal.xml
  agijagi/app/src/main/res/drawable/outline_storefront_24_nomal.xml
  agijagi/app/src/main/res/layout/fragment_google_signup_buyer.xml
  agijagi/app/src/main/res/layout/fragment_google_signup_seller.xml
  agijagi/app/src/main/res/layout/fragment_login.xml
  agijagi/app/src/main/res/layout/fragment_no_login_mypage.xml
  agijagi/app/src/main/res/layout/fragment_signup.xml
  agijagi/app/src/main/res/layout/fragment_signup_buyer.xml
  agijagi/app/src/main/res/layout/fragment_signup_select.xml
  agijagi/app/src/main/res/layout/fragment_signup_seller.xml
  agijagi/app/src/main/res/menu/menu_bottom_navigation_mainactivity.xml
  agijagi/app/src/main/res/navigation/navigation_graph.xml
  agijagi/app/src/main/res/values/strings.xml
Labels: Feat

#142 Design: 스토어관리 UI 수정 #133
  agijagi/app/src/main/res/layout/fragment_store_management.xml
Labels: Design

#147 Feature: navigation back stack 처리 #139
  agijagi/app/src/main/java/likelion/project/agijagi/MainActivity.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/ProfileManagementFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/ShippingAddFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/ShippingManagementFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/ShippingUpdateFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/category/CategoryDetailInfoListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/category/CategoryFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/category/OrderMadeCategoryFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/chatting/ChattingListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/chatting/ChattingRoomFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/deliverytracking/DeliveryTrackingFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/home/HomeFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/login/LoginFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/notification/NotificationListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/product/CustomProductDetailFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/product/ProductDetailFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/productoption/CustomOptionFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/productoption/ReadyMadeOptionFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/purchase/PaymentFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/purchase/PurchaseCompleteFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/search/SearchFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/OrderManagementDetailFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/OrderManagementFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductAddFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductDetailPreviewFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductUpdateFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/SellerMypageFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/SellerNotificationSettingFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/SellerProductDetailFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/StoreManagementFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/shopping/ShoppingListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/SignupBuyerFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/SignupSelectFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/SignupSellerFragment.kt
  agijagi/app/src/main/res/layout/fragment_category_detail_info_list.xml
  agijagi/app/src/main/res/layout/fragment_order_management.xml
  agijagi/app/src/main/res/layout/fragment_order_management_detail.xml
  agijagi/app/src/main/res/layout/fragment_product_add.xml
  agijagi/app/src/main/res/layout/fragment_product_update.xml
Labels: Feat

#149 Remove: fragment_category_detail.xml 삭제 #148
  agijagi/app/src/main/res/layout/fragment_category_detail.xml
Labels: Remove

#151 Rename: JoinDataVo -> SignupModel로 파일명 변경 #150
  agijagi/app/src/main/java/likelion/project/agijagi/signup/SignupModel.kt
Labels: Rename

#154 Feat: 상품리스트 기능추가 #145
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/adapter/ProductListAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/model/ProductListModel.kt
  agijagi/app/src/main/res/layout/item_product_list.xml
  agijagi/app/src/main/res/values/array.xml
Labels: Feat

#159 Feat: 체크 박스 동작 처리와 리스트 삭제 처리 #138
  agijagi/app/src/main/java/likelion/project/agijagi/notification/NotificationListAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/notification/NotificationListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductAddFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductUpdateFragment.kt
  agijagi/app/src/main/res/drawable/adjust_24px.xml
  agijagi/app/src/main/res/drawable/shopping_list_circle_checkbox_selector.xml
  agijagi/app/src/main/res/layout/fragment_notification_list.xml
  agijagi/app/src/main/res/layout/item_notification_list.xml
Labels: Feat

#162 Feat: Notification dialog #160
  agijagi/app/src/main/java/likelion/project/agijagi/notification/NotificationListAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/notification/NotificationListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/notification/NotificationListModel.kt
  agijagi/app/src/main/res/layout/dialog_notification_message_custom.xml
  agijagi/app/src/main/res/layout/item_notification_list.xml
Labels: Feat

#163 Feat: 배송지등록 기능추가 #155
  agijagi/.idea/gradle.xml
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/ShippingAddFragment.kt
Labels: Feat

#166 Feat: 검색 중 리스트 수정 #52
  agijagi/app/src/main/java/likelion/project/agijagi/search/SearchFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/search/adapter/RecentSearchAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/search/adapter/SearchAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/search/adapter/SearchResultAdapter.kt
  agijagi/app/src/main/res/drawable/search_brown_24px.xml
  agijagi/app/src/main/res/layout/fragment_search.xml
  agijagi/app/src/main/res/layout/item_search.xml
Labels: Feat

#167 Refactor: user essential class 추가 #165
  agijagi/app/src/main/java/likelion/project/agijagi/UserEssential.kt
Labels: Refactor

#168 Feat: 판매자 알림 설정 화면 기능 구현 #161
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/SellerNotificationSettingFragment.kt
  agijagi/app/src/main/res/layout/fragment_seller_notification_setting.xml
Labels: Feat

#171 Feat: 검색어 입력 중 기능 구현 (mvvm)
  agijagi/app/build.gradle
  agijagi/app/src/main/java/likelion/project/agijagi/search/SearchFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/search/adapter/SearchAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/search/repository/SearchRepository.kt
  agijagi/app/src/main/java/likelion/project/agijagi/search/vm/SearchViewModel.kt
  agijagi/app/src/main/res/layout/fragment_search.xml
Labels: Feat

#174 Design: 검색 결과 화면 UI #172
  agijagi/app/src/main/java/likelion/project/agijagi/search/SearchResultFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/search/adapter/SearchAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/search/repository/SearchRepository.kt
  agijagi/app/src/main/res/layout/fragment_search.xml
  agijagi/app/src/main/res/layout/fragment_search_result.xml
  agijagi/app/src/main/res/navigation/navigation_graph.xml
Labels: Design

#177 Feat: 배송지관리 기능추가 #157
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/ShippingAddFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/ShippingManagementFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/adapter/ShippingManagementAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/model/ShippingManagementModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/repository/ShippingManagementRepository.kt
  agijagi/app/src/main/res/layout/fragment_shipping_management.xml
  agijagi/app/src/main/res/layout/item_shipping_management.xml
Labels: Feat, Design

#178 Feat: product detail preview DB 연결 #175
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductDetailPreviewFragment.kt
Labels: Feat

#179 Feat: 알림리스트 화면 서버 연동 #170
  agijagi/app/src/main/java/likelion/project/agijagi/notification/NotificationListAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/notification/NotificationListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/notification/NotificationListModel.kt
Labels: Feat

#183 Feat: CustomOption 이미지 로딩 구현 #141
  agijagi/app/src/main/java/likelion/project/agijagi/productoption/CustomOptionFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/productoption/CustomOptionModel.kt
  agijagi/app/src/main/res/drawable/cancel_agijagi2.png
  agijagi/app/src/main/res/layout/fragment_custom_option.xml
  agijagi/app/src/main/res/layout/item_custom_option_back.xml
  agijagi/app/src/main/res/layout/item_custom_option_front.xml
  agijagi/app/src/main/res/layout/item_custom_option_left.xml
  agijagi/app/src/main/res/layout/item_custom_option_right.xml
Labels: Feat

#185 Feat: signup, login 기능 변경, mypage ui 수정 #146
  agijagi/app/build.gradle
  agijagi/app/src/main/java/likelion/project/agijagi/MainActivity.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/BuyerMypageFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/login/LoginFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/SellerMypageFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/SignupBuyerFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/SignupGoogleBuyerFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/SignupGoogleSellerFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/SignupSelectFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/ui/SignupBuyerFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/ui/SignupGoogleBuyerFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/ui/SignupGoogleSellerFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/ui/SignupSelectFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/ui/SignupSellerFragment.kt
  agijagi/app/src/main/res/drawable/bowl_thumbnail.jpg
  agijagi/app/src/main/res/drawable/cup_thumbnail.jpg
  agijagi/app/src/main/res/drawable/order_made_bowl_thumbnail.jpg
  agijagi/app/src/main/res/drawable/order_made_cup_thumbnail.jpg
  agijagi/app/src/main/res/drawable/order_made_plate_thumbnail.jpg
  agijagi/app/src/main/res/drawable/order_made_thumbnail.jpg
  agijagi/app/src/main/res/drawable/plate_thumbnail.jpg
  agijagi/app/src/main/res/layout/fragment_google_signup_buyer.xml
  agijagi/app/src/main/res/layout/fragment_google_signup_seller.xml
  agijagi/app/src/main/res/layout/fragment_login.xml
  agijagi/app/src/main/res/layout/fragment_signup_buyer.xml
  agijagi/app/src/main/res/layout/fragment_signup_select.xml
  agijagi/app/src/main/res/layout/fragment_signup_seller.xml
  agijagi/app/src/main/res/navigation/navigation_graph.xml
Labels: Feat

#189 Refactor: separate model #188
  agijagi/app/src/main/java/likelion/project/agijagi/model/BuyerModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/model/ChattingRoomModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/model/NotifInfoModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/model/OrderModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/model/ProductModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/model/SellerModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/model/UserModel.kt
Labels: Refactor

#195 Fix: 시스템 백버튼 오류 해결 #164
  agijagi/app/src/main/java/likelion/project/agijagi/MainActivity.kt
Labels: Fix

#194 Design: CustomOption 구분선, 스크롤뷰 수정 #187
  agijagi/app/src/main/AndroidManifest.xml
  agijagi/app/src/main/java/likelion/project/agijagi/productoption/CustomOptionFragment.kt
  agijagi/app/src/main/res/layout/fragment_custom_option.xml
  agijagi/app/src/main/res/values/array.xml
Labels: Design

#196 Design: login tool bar #191
  agijagi/app/src/main/res/layout/fragment_login.xml
Labels: Design

#197 Feat: 기본배송지 설정 기능 추가 #157
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/ShippingAddFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/ShippingManagementFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/adapter/ShippingManagementAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/model/ShippingManagementModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/repository/ShippingManagementRepository.kt
  agijagi/app/src/main/res/layout/item_shipping_management.xml
Labels: Feat, Design

#201 Feat: signup buyer db 추가, seller db 수정 #193
  agijagi/app/src/main/java/likelion/project/agijagi/signup/ui/SignupBuyerFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/ui/SignupSellerFragment.kt
  agijagi/app/src/main/res/navigation/navigation_graph.xml
Labels: Feat

#202 Feat: 배송지수정 기능추가 #156
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/ShippingUpdateFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/adapter/ShippingManagementAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/repository/ShippingManagementRepository.kt
Labels: Feat

#203 Feat: 판매자 상품 등록 -> 상품 상세 미리보기 프로세스 데이터 전달 및 수신 #176
  agijagi/app/src/main/java/likelion/project/agijagi/model/ProductModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductAddFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductDetailPreviewFragment.kt
Labels: Feat

#205 Feat: 상품 상세 미리보기 view 셋팅, 상품 DB 등록 #204
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductDetailPreviewFragment.kt
Labels: Feat

#207 Feat: 기성품 및 커스텀 상품 상세화면 -> 옵션 선택으로 상품번호 전달 #206
  agijagi/app/src/main/java/likelion/project/agijagi/product/CustomProductDetailFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/product/ProductDetailFragment.kt
Labels: Feat

#212 Feature: 버그 수정, 상품 정보 db칼럼 변경 내용 적용
  agijagi/app/src/main/java/likelion/project/agijagi/model/ProductModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductAddFragment.kt
Labels: Feat

#213 Feat: login 유효성 기능 추가 #192
  agijagi/app/src/main/java/likelion/project/agijagi/login/LoginFragment.kt
Labels: Feat

#221 Fix: 상품 상세 미리보기product model 관련 변수 typo #217
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductDetailPreviewFragment.kt
Labels: Fix

#223 Refactor: user essential 파일 삭제 및 getMilliSec() 이동 #190
  agijagi/app/src/main/java/likelion/project/agijagi/MainActivity.kt
  agijagi/app/src/main/java/likelion/project/agijagi/UserEssential.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/ShippingAddFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/ShippingManagementFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/model/BuyerModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/model/SellerModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/model/UserModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductDetailPreviewFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/SellerNotificationSettingFragment.kt
Labels: Fix, Refactor

#228 Design: ProductDetailPreview imageview 추가 #227
  agijagi/app/src/main/res/layout/fragment_product_detail_preview.xml
Labels: Design

#229 Feat: 상품리스트 DB 기능 추가 #209
  agijagi/app/build.gradle
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/adapter/ProductListAdapter.kt
  agijagi/app/src/main/res/layout/fragment_product_list.xml
  agijagi/app/src/main/res/layout/item_product_list_shimmer.xml
Labels: Feat, Design

#231 Feat: ProductDetailPreview 상품 이미지뷰 셋팅, 상품 이미지&도면 등록 기능 구현 #222
  agijagi/app/build.gradle
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductDetailPreviewFragment.kt
  agijagi/app/src/main/res/layout/fragment_custom_product_detail.xml
  agijagi/app/src/main/res/layout/fragment_product_detail_preview.xml
Labels: Feat

#232 Feat: 상품 등록, 수정 화면 UI 기능 수정 #224
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductAddFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductUpdateFragment.kt
  agijagi/app/src/main/res/layout/fragment_product_add.xml
  agijagi/app/src/main/res/layout/fragment_product_update.xml
  agijagi/app/src/main/res/values/array.xml
Labels: Feat

#236 Fix: Google signup, login bug fix #235
  agijagi/app/build.gradle
  agijagi/app/src/main/java/likelion/project/agijagi/login/LoginFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/ui/SignupGoogleBuyerFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/ui/SignupGoogleSellerFragment.kt
  agijagi/app/src/main/res/layout/fragment_signup_buyer.xml
  agijagi/app/src/main/res/values/strings.xml
Labels: Fix

#237 Feat: 기성품 상세 화면 상품 정보 로드 기능 구현 #233
  agijagi/app/build.gradle
  agijagi/app/src/main/java/likelion/project/agijagi/product/ProductDetailFragment.kt
  agijagi/app/src/main/res/layout/fragment_product_detail.xml
Labels: Feat

#239 Feat: 커스텀 상품 상세 화면 상품 정보 로드 기능 구현 #238
  agijagi/app/src/main/java/likelion/project/agijagi/product/CustomProductDetailFragment.kt
  agijagi/app/src/main/res/layout/fragment_custom_product_detail.xml
Labels: Feat

#243 Feat: 상품 상세 미리보기 이미지 placeholder 추가 #240
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductDetailPreviewFragment.kt
Labels: Feat

#244 Feat: signup 관련 3개 scrollview 추가
  agijagi/app/src/main/java/likelion/project/agijagi/signup/ui/SignupBuyerFragment.kt
  agijagi/app/src/main/res/layout/fragment_google_signup_seller.xml
  agijagi/app/src/main/res/layout/fragment_signup_buyer.xml
  agijagi/app/src/main/res/layout/fragment_signup_seller.xml
Labels: Feat

#248 Feat: 판매자 상품 상세 화면 상품 정보 로드 기능 구현 #247
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/SellerProductDetailFragment.kt
  agijagi/app/src/main/res/layout/fragment_seller_product_detail.xml
Labels: Feat

#249 Feat: 스플래시 스크린 #246
  agijagi/app/src/main/AndroidManifest.xml
  agijagi/app/src/main/java/likelion/project/agijagi/MainActivity.kt
  agijagi/app/src/main/java/likelion/project/agijagi/SplashScreenActivity.kt
  agijagi/app/src/main/res/anim/splash_alpha.xml
  agijagi/app/src/main/res/layout/activity_splash_screen.xml
  agijagi/app/src/main/res/values/themes.xml
Labels: Feat

#250 Design: addlogin app banner, scrollview #245
  agijagi/app/src/main/res/layout/fragment_login.xml
Labels: Design

#251 Feat: 기성품, 커스텀 상품 상세 화면 찜 버튼 기능 구현 #198
  agijagi/app/src/main/java/likelion/project/agijagi/product/CustomProductDetailFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/product/ProductDetailFragment.kt
  agijagi/app/src/main/res/layout/fragment_product_detail.xml
Labels: Feat

#252 Design: home bestitem items size 조절 #216
  agijagi/app/src/main/res/layout/fragment_home.xml
Labels: Design

#255 Fix: signup null 값 입력시 오류 해결 #214
  agijagi/app/src/main/java/likelion/project/agijagi/signup/ui/SignupBuyerFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/ui/SignupSellerFragment.kt
Labels: Fix

#257 Feat: signup에서 snackbar가 view 가리는 현상 제거 #256
  agijagi/app/src/main/java/likelion/project/agijagi/signup/ui/SignupBuyerFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/ui/SignupGoogleBuyerFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/ui/SignupGoogleSellerFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/ui/SignupSellerFragment.kt
Labels: Feat

#258 Design: 아이콘 크기 조정 #246
  agijagi/app/src/main/res/layout/activity_splash_screen.xml
Labels: Design

#260 Feat: 검색바 초기화 & 최근 검색어 클릭 시 화면 전환 기능 구현 #254
  agijagi/app/src/main/java/likelion/project/agijagi/search/SearchFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/search/adapter/RecentSearchAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/search/adapter/SearchAdapter.kt
Labels: Feat

#261 Feat: get Login user db #259
  agijagi/app/src/main/java/likelion/project/agijagi/MainActivity.kt
  agijagi/app/src/main/java/likelion/project/agijagi/home/HomeFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/login/LoginFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/model/UserModel.kt
Labels: Feat

#264 FIx: seller login 했을 때 user db 데이터 확인 #263
  agijagi/app/src/main/java/likelion/project/agijagi/login/LoginFragment.kt
Labels: Fix

#267 Feat: PaymentFragment DB 서버연결 #184
  agijagi/app/src/main/java/likelion/project/agijagi/model/OrderModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/productoption/CustomOptionFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/purchase/PaymentFragment.kt
Labels: Feat

#270 Feat: 검색 리스트 중복값 제거 #269
  agijagi/app/src/main/java/likelion/project/agijagi/search/SearchFragment.kt
Labels: Feat

#272 Feat: 커스텀 상품 상세 페이지 상품 Id 수신 및 전달 수정 #271
  agijagi/app/src/main/java/likelion/project/agijagi/product/CustomProductDetailFragment.kt
Labels: Feat

#274 Feat: 커스텀 여부에 따른 상품 상세 화면 전환(검색결과화면) #273
  agijagi/app/src/main/java/likelion/project/agijagi/search/SearchResultFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/search/SearchResultModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/search/adapter/SearchResultAdapter.kt
Labels: Feat

#277 Design: 커스텀 상품 상세 화면 수정 #276
  agijagi/app/src/main/res/layout/fragment_custom_product_detail.xml
Labels: Design

#280 Feat: 결제페이지 배송지 변경 기능 #234
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/ShippingManagementFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/ShippingUpdateFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/adapter/ShippingManagementAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/repository/ShippingManagementRepository.kt
  agijagi/app/src/main/java/likelion/project/agijagi/model/BuyerModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/purchase/PaymentFragment.kt
  agijagi/app/src/main/res/layout/item_shipping_management.xml
Labels: Feat, Design

#281 Feat: categoryList Item db 정보 받기 #218
  agijagi/app/src/main/java/likelion/project/agijagi/MainActivity.kt
  agijagi/app/src/main/java/likelion/project/agijagi/category/CategoryDetailInfoListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/category/CategoryDetailInfoListModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/category/CategoryFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/category/OrderMadeCategoryFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/category/adapter/CategoryDetailInfoListAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/category/model/CategoryDetailInfoListModel.kt
  agijagi/app/src/main/res/layout/fragment_category.xml
  agijagi/app/src/main/res/layout/fragment_category_detail_info_list.xml
  agijagi/app/src/main/res/layout/fragment_order_made_category.xml
Labels: Feat

#285 Feat: 상품 등록 화면 기능 수정 #253
  agijagi/app/src/main/java/likelion/project/agijagi/model/ProductModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductAddFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductUpdateFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/model/ProductAddModel.kt
  agijagi/app/src/main/res/layout/fragment_product_add.xml
  agijagi/app/src/main/res/layout/fragment_product_update.xml
Labels: Feat

#287 Feat: 판매자 상품 상세 화면 상품 데이터 수신 및 상품 수정화면으로 전달#278
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductUpdateFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/SellerProductDetailFragment.kt
Labels: Feat

#288 Feat: 삭제했던 주문제작 여부 선택 드롭다운 재작업 #284
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductAddFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductUpdateFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/model/ProductUpdateModel.kt
  agijagi/app/src/main/res/layout/fragment_product_add.xml
  agijagi/app/src/main/res/layout/fragment_product_update.xml
  agijagi/app/src/main/res/layout/item_product_add_add_picture.xml
  agijagi/app/src/main/res/values/array.xml
Labels: Feat

#293 Feat: 로그인 했을 때 user db 받는 정보 추가 #286
  agijagi/app/src/main/java/likelion/project/agijagi/MainActivity.kt
  agijagi/app/src/main/java/likelion/project/agijagi/login/LoginFragment.kt
Labels: Feat

#295 Fix: homeFramgnet bug fix #294
  agijagi/app/src/main/java/likelion/project/agijagi/home/HomeFragment.kt
Labels: Fix

#297 Fix: categoryList db 받는 정보 변경#282
  agijagi/app/src/main/java/likelion/project/agijagi/category/CategoryDetailInfoListFragment.kt
Labels: Fix

#299 Feat: 로그인 여부에 따른 상품 상세 페이지 버튼 설정 #289
  agijagi/app/src/main/java/likelion/project/agijagi/MainActivity.kt
  agijagi/app/src/main/java/likelion/project/agijagi/product/ProductDetailFragment.kt
Labels: Feat

#301 Feat: 커스텀 상품 상세 화면 로그인 여부에 따른 버튼 설정 #300
  agijagi/app/src/main/java/likelion/project/agijagi/product/CustomProductDetailFragment.kt
Labels: Feat

#304 Feat: category 중복 데이터 제거 #283
  agijagi/app/src/main/java/likelion/project/agijagi/category/CategoryDetailInfoListFragment.kt
Labels: Feat

#307 Feat: 로그인 다이얼로그 버튼 화면 이동 #302
  agijagi/app/src/main/java/likelion/project/agijagi/MainActivity.kt
  agijagi/app/src/main/java/likelion/project/agijagi/login/LoginFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/product/CustomProductDetailFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/product/ProductDetailFragment.kt
  agijagi/app/src/main/res/navigation/navigation_graph.xml
Labels: Feat

#309 Feat: 상품 가격 형변환 #308
  agijagi/app/src/main/java/likelion/project/agijagi/product/CustomProductDetailFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/product/ProductDetailFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/search/adapter/SearchResultAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductDetailPreviewFragment.kt
Labels: Feat

#311 Feat: 상품 수정 화면 이미지 다운로드 #290
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductUpdateFragment.kt
Labels: Feat

#312 Feat: 결제페이지 기능 추가 #279
  agijagi/app/src/main/java/likelion/project/agijagi/model/OrderModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/purchase/PaymentFragment.kt
  agijagi/app/src/main/res/layout/fragment_payment.xml
Labels: Feat, Design

#313 Feat: 구매자 알림설정 화면 기능 구현 #291
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/BuyerNotificationSettingFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/SellerNotificationSettingFragment.kt
  agijagi/app/src/main/res/layout/fragment_buyer_notification_setting.xml
Labels: Feat

#314 Feat: 상품 품절상태일때 구매하기 버튼 비활성화 #310
  agijagi/app/src/main/java/likelion/project/agijagi/product/CustomProductDetailFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/product/ProductDetailFragment.kt
  agijagi/app/src/main/res/drawable/wide_box_rounded_purchase_button_inactive.xml
Labels: Feat

#318 Design: category List item ui 변경 #215
  agijagi/app/src/main/java/likelion/project/agijagi/category/adapter/CategoryDetailInfoListAdapter.kt
  agijagi/app/src/main/res/drawable/category_list_item_default_image.png
  agijagi/app/src/main/res/layout/item_category_detail_info_list.xml
  agijagi/app/src/main/res/layout/item_category_list_shimmer.xml
Labels: Design

#323 Fix: CustomOption 데이터 수정 #275
  agijagi/app/src/main/java/likelion/project/agijagi/productoption/CustomOptionFragment.kt
Labels: Fix

#324 Fix: CustomOption 데이터 수정 #275
  agijagi/app/src/main/java/likelion/project/agijagi/productoption/CustomOptionFragment.kt
Labels: Fix

#326 Feat: 페이지 이동 시 로그인 확인 동작 #319
  agijagi/app/src/main/java/likelion/project/agijagi/MainActivity.kt
  agijagi/app/src/main/java/likelion/project/agijagi/home/HomeFragment.kt
Labels: Feat

#327 Feat: category list loading 생성 #298
  agijagi/app/src/main/java/likelion/project/agijagi/category/CategoryDetailInfoListFragment.kt
  agijagi/app/src/main/res/layout/fragment_category_detail_info_list.xml
  agijagi/app/src/main/res/layout/item_category_list_shimmer.xml
Labels: Feat

#328 Fix: 회원가입 관련 백버튼 버그 수정 #325
  agijagi/app/src/main/java/likelion/project/agijagi/signup/ui/SignupGoogleBuyerFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/ui/SignupGoogleSellerFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/ui/SignupSelectFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/ui/SignupSellerFragment.kt
  agijagi/app/src/main/res/navigation/navigation_graph.xml
Labels: Fix

#332 Feat: 구매자 mypage 수정 #315
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/BuyerMypageFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/model/UserModel.kt
Labels: Feat

#334 Feat: 결제완료화면 기능 #279
  agijagi/app/src/main/java/likelion/project/agijagi/purchase/PaymentFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/purchase/PurchaseCompleteFragment.kt
  agijagi/app/src/main/res/layout/fragment_payment.xml
  agijagi/app/src/main/res/layout/fragment_purchase_complete.xml
Labels: Feat, Design

#336 Fix: 배송지관리 DB 수정 #335
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/ShippingAddFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/ShippingManagementFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/repository/ShippingManagementRepository.kt
Labels: Fix

#339 Design: 채팅룸 UI 수정 #317
  agijagi/app/src/main/java/likelion/project/agijagi/chatting/ChattingRoomAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/chatting/ChattingRoomFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/model/ChattingRoomModel.kt
  agijagi/app/src/main/res/layout/fragment_chatting_room.xml
  agijagi/app/src/main/res/layout/item_chatting_room_my_chat.xml
  agijagi/app/src/main/res/layout/item_chatting_room_other_chat.xml
Labels: Design

#340 Feat: Category Shimmer ui 변경 & 코드 수정 #298
  agijagi/app/src/main/java/likelion/project/agijagi/category/CategoryDetailInfoListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/productoption/product/CustomProductDetailFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/productoption/product/ProductDetailFragment.kt
  agijagi/app/src/main/res/layout/fragment_category_detail_info_list.xml
  agijagi/app/src/main/res/layout/fragment_custom_product_detail.xml
  agijagi/app/src/main/res/layout/fragment_product_detail.xml
  agijagi/app/src/main/res/layout/item_category_list_shimmer.xml
  agijagi/app/src/main/res/navigation/navigation_graph.xml
Labels: Feat

#341 Feat: 내 정보 수정 기능 구현 #316
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/ProfileManagementFragment.kt
  agijagi/app/src/main/res/layout/fragment_profile_management.xml
Labels: Feat

#343 Fix: 상품리스트 DB 수정 #338
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/adapter/ProductListAdapter.kt
  agijagi/app/src/main/res/layout/item_product_list_shimmer.xml
Labels: Design, Fix

#344 Feat: 브랜드 정보 수정 화면 기능 구현 #331
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/StoreManagementFragment.kt
  agijagi/app/src/main/res/layout/fragment_store_management.xml
Labels: Feat

#346 Feat: 채팅 텍스트 전송 기능 구현 #320
  agijagi/app/src/main/java/likelion/project/agijagi/MainActivity.kt
  agijagi/app/src/main/java/likelion/project/agijagi/chatting/ChattingRoomAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/chatting/ChattingRoomFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/productoption/product/CustomProductDetailFragment.kt
  agijagi/app/src/main/res/layout/fragment_chatting_room.xml
  agijagi/app/src/main/res/navigation/navigation_graph.xml
Labels: Feat

#350 Rename: Product 파일 이동 #348
  agijagi/app/src/main/java/likelion/project/agijagi/product/CustomProductDetailFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/product/ProductDetailFragment.kt
  agijagi/app/src/main/res/layout/fragment_custom_product_detail.xml
  agijagi/app/src/main/res/layout/fragment_product_detail.xml
  agijagi/app/src/main/res/navigation/navigation_graph.xml
Labels: Rename

#351 Feat: seller buyer db 정보 받기 #342
  agijagi/app/src/main/java/likelion/project/agijagi/home/HomeFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/login/LoginFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/model/BuyerModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/model/SellerModel.kt
  agijagi/app/src/main/res/layout/fragment_category_detail_info_list.xml
Labels: Feat

#353 Feat: 알림리스트에서 채팅방 이동 기능 #345
  agijagi/app/src/main/java/likelion/project/agijagi/notification/NotificationListAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/notification/NotificationListFragment.kt
  agijagi/app/src/main/res/navigation/navigation_graph.xml
Labels: Feat

#357 Feat: 채팅 기능 구현 #356
  agijagi/app/src/main/java/likelion/project/agijagi/chatting/ChattingListAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/chatting/ChattingListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/chatting/ChattingListModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/chatting/ChattingRoomAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/chatting/ChattingRoomFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/product/CustomProductDetailFragment.kt
  agijagi/app/src/main/res/layout/fragment_chatting_list.xml
  agijagi/app/src/main/res/layout/fragment_chatting_room.xml
Labels: Feat

#358 Feat: 상품 배송 화면 기능 구현 #354
  agijagi/app/src/main/AndroidManifest.xml
  agijagi/app/src/main/java/likelion/project/agijagi/deliverytracking/DeliveryTrackingFragment.kt
  agijagi/app/src/main/res/drawable/order_delivery_complete_selector.xml
  agijagi/app/src/main/res/drawable/order_delivery_ready_selector.xml
  agijagi/app/src/main/res/drawable/order_delivery_selector.xml
  agijagi/app/src/main/res/layout/fragment_delivery_tracking.xml
Labels: Feat

#361 Feat: product model 항목 추가 및 상품 등록 brand, roleId 값 수정 #359
  agijagi/app/src/main/java/likelion/project/agijagi/login/LoginFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/model/ProductModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductDetailPreviewFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/SellerProductDetailFragment.kt
Labels: Feat

#362 Feat: 알림리스트에서 발신자를 이름이 아닌 PK로 찾는 기능 #360
  agijagi/app/src/main/java/likelion/project/agijagi/notification/NotificationListAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/notification/NotificationListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/notification/NotificationListModel.kt
Labels: Feat

#363 Feat: google login 시 db 받기 #342
  agijagi/app/src/main/java/likelion/project/agijagi/login/LoginFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/ui/SignupGoogleBuyerFragment.kt
Labels: Feat

#366 Fix: price format 수정 #275
  agijagi/app/src/main/java/likelion/project/agijagi/productoption/CustomOptionFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/SellerProductDetailFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/shopping/ShoppingListAdapter.kt
Labels: Fix

#367 Feat: 주문/배송 조회 기능 구현 #337
  agijagi/app/src/main/java/likelion/project/agijagi/order/OrderAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/order/OrderFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/order/OrderModel.kt
  agijagi/app/src/main/res/layout/fragment_order.xml
  agijagi/app/src/main/res/layout/item_order.xml
  agijagi/app/src/main/res/layout/item_order_date.xml
  agijagi/app/src/main/res/layout/item_order_shimmer.xml
Labels: Feat, Design, Remove

#368 Feat: homeFragment bestItem shimmer & 잘 팔린 상품으로 등록 #303
  agijagi/app/src/main/java/likelion/project/agijagi/category/CategoryDetailInfoListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/category/adapter/CategoryDetailInfoListAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/home/HomeFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/home/adapter/BestItemAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/model/CategoryDetailInfoListModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/model/HomeBestItemModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductUpdateFragment.kt
  agijagi/app/src/main/res/layout/fragment_home.xml
  agijagi/app/src/main/res/layout/item_home_best_item.xml
  agijagi/app/src/main/res/layout/item_home_bestitem_shimmer.xml
  agijagi/app/src/main/res/layout/item_home_logo_shimmer.xml
  agijagi/app/src/main/res/navigation/navigation_graph.xml
Labels: Feat

#370 Feat: Wish List 구현 #369
  agijagi/app/src/main/java/likelion/project/agijagi/wishlist/WishListAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/wishlist/WishListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/wishlist/WishListModel.kt
  agijagi/app/src/main/res/layout/fragment_wish_list.xml
  agijagi/app/src/main/res/layout/item_wish_list.xml
  agijagi/app/src/main/res/layout/item_wish_list_shimmer.xml
Labels: Feat

#373 Feat: 상품 수정 및 삭제 기능 구현 #321
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductDetailPreviewFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductUpdateDetailPreviewFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductUpdateFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/SellerProductDetailFragment.kt
Labels: Feat

#374 Refactor: Code cleanup #355
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/BuyerMypageFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/BuyerNotificationSettingFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/ShippingAddFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/ShippingManagementFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/ShippingUpdateFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/adapter/ShippingManagementAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/model/ShippingManagementModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/category/CategoryDetailInfoListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/category/CategoryFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/category/OrderMadeCategoryFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/chatting/ChattingListAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/chatting/ChattingListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/chatting/ChattingRoomFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/deliverytracking/DeliveryTrackingFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/home/HomeFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/login/LoginFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/notification/NotificationListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/order/OrderFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/product/CustomProductDetailFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/product/ProductDetailFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/productoption/CustomOptionFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/purchase/PaymentFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/purchase/PurchaseCompleteFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/search/SearchFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/search/adapter/RecentSearchAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/search/vm/SearchViewModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/OrderManagementDetailFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductAddFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductDetailPreviewFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductUpdateDetailPreviewFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductUpdateFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/SellerNotificationSettingFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/StoreManagementFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/adapter/ProductListAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/model/ProductListModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/shopping/ShoppingListAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/shopping/ShoppingListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/SignupBuyerFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/SignupGoogleBuyerFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/SignupGoogleSellerFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/SignupSelectFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/SignupSellerFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/model/SignupModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/wishlist/WishListAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/wishlist/WishListFragment.kt
  agijagi/app/src/main/res/layout/fragment_custom_product_detail.xml
  agijagi/app/src/main/res/layout/fragment_google_signup_buyer.xml
  agijagi/app/src/main/res/layout/fragment_google_signup_seller.xml
  agijagi/app/src/main/res/layout/fragment_product_detail.xml
  agijagi/app/src/main/res/layout/fragment_signup_select.xml
  agijagi/app/src/main/res/layout/fragment_signup_seller.xml
  agijagi/app/src/main/res/navigation/navigation_graph.xml
Labels: Refactor

#377 Feat: 상품리스트 삭제상태 DB코드추가 #371
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductListFragment.kt
Labels: Feat

#378 Fix: Wish List 중복제거 #369
  agijagi/app/src/main/java/likelion/project/agijagi/wishlist/WishListFragment.kt
Labels: Fix

#381 Fix: Order -> Chat navigation update #379
  agijagi/app/src/main/java/likelion/project/agijagi/order/OrderAdapter.kt
  agijagi/app/src/main/res/navigation/navigation_graph.xml
Labels: Fix

#382 Feat: home, category 가격 포맷팅 #380
  agijagi/app/src/main/java/likelion/project/agijagi/category/adapter/CategoryDetailInfoListAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/home/HomeFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/home/adapter/BestItemAdapter.kt
Labels: Feat

#385 Fix: 상품 등록 및 수정 기능 버그 수정 #380
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductDetailPreviewFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductUpdateDetailPreviewFragment.kt
Labels: Fix

#387 Fix: customImage #372
  agijagi/app/src/main/res/layout/fragment_custom_option.xml
Labels: Fix

#389 Fix: shoppingListImage #372
  agijagi/app/src/main/res/layout/item_shopping_list.xml
Labels: Fix

#384 Feat: Login 시 Category List에서 favorite 표기 # 305
  agijagi/app/src/main/java/likelion/project/agijagi/category/CategoryDetailInfoListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/category/adapter/CategoryDetailInfoListAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/model/CategoryDetailInfoListModel.kt
  agijagi/app/src/main/res/layout/item_category_detail_info_list.xml
Labels: Feat
