Repository APPSCHOOL2-Android/FinalProject-ShoppingMallService-team4, pull requests merged in 2023-08, with the labels that each got.

#12 [Design] 바텀네비게이션 추가
  agijagi/.gitignore
  agijagi/app/src/main/java/likelion/project/agijagi/MainActivity.kt
  agijagi/app/src/main/res/drawable/favorite_24px.xml
  agijagi/app/src/main/res/drawable/home_24px.xml
  agijagi/app/src/main/res/drawable/local_shipping_24px.xml
  agijagi/app/src/main/res/drawable/menu_24px.xml
  agijagi/app/src/main/res/drawable/person_24px.xml
  agijagi/app/src/main/res/drawable/shopping_bag_24px.xml
  agijagi/app/src/main/res/layout/activity_main.xml
  agijagi/app/src/main/res/layout/fragment_shopping_list.xml
  agijagi/app/src/main/res/menu/bottom_navigation_menu.xml
  agijagi/app/src/main/res/values/strings.xml
Labels: Design

#13 Design: Add Login Ui #2
  agijagi/app/google-services.json
  agijagi/app/src/main/java/likelion/project/agijagi/signup/SignupSelectFragment.kt
  agijagi/app/src/main/res/drawable/google_login.png
  agijagi/app/src/main/res/drawable/outline_person_outline_24_nomal.xml
  agijagi/app/src/main/res/drawable/outline_person_outline_24_selected.xml
  agijagi/app/src/main/res/drawable/outline_storefront_24_nomal.xml
  agijagi/app/src/main/res/drawable/outline_storefront_24_selected.xml
  agijagi/app/src/main/res/drawable/signup_box_rounded_selected_button.xml
  agijagi/app/src/main/res/drawable/thunbnail.png
  agijagi/app/src/main/res/drawable/wide_box_rounded_button_stroke.xml
  agijagi/app/src/main/res/drawable/wide_box_rounded_stroke.xml
  agijagi/app/src/main/res/layout/fragment_home.xml
  agijagi/app/src/main/res/layout/fragment_login.xml
  agijagi/app/src/main/res/layout/fragment_signup_select.xml
  test.txt
Labels: Design

#14 Design: Add signup seller/buyer ui #2
  agijagi/app/src/main/java/likelion/project/agijagi/signup/SignupSellerFragment.kt
  agijagi/app/src/main/res/drawable/arrow_back_24px.xml
  agijagi/app/src/main/res/drawable/small_box_rounded_button_stroke.xml
  agijagi/app/src/main/res/drawable/wide_box_selected_active.xml
  agijagi/app/src/main/res/layout/fragment_google_signup_buyer.xml
  agijagi/app/src/main/res/layout/fragment_google_signup_seller.xml
  agijagi/app/src/main/res/layout/fragment_login.xml
  agijagi/app/src/main/res/layout/fragment_signup_buyer.xml
  agijagi/app/src/main/res/layout/fragment_signup_select.xml
  agijagi/app/src/main/res/layout/fragment_signup_seller.xml
  agijagi/app/src/main/res/values/colors.xml
Labels: Design

#24 Fix: ShoppingList를 WishList로 수정 #5
  agijagi/app/build.gradle
  agijagi/app/src/main/java/likelion/project/agijagi/wishlist/WishListAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/wishlist/WishListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/wishlist/WishListModel.kt
  agijagi/app/src/main/res/drawable/wish_list_logo.png
  agijagi/app/src/main/res/layout/fragment_wish_list.xml
  agijagi/app/src/main/res/layout/item_wish_list.xml
  agijagi/app/src/main/res/menu/menu_wish_list.xml
  agijagi/app/src/main/res/navigation/navigation_graph.xml
Labels: Fix

#25 Design: 배송조회, 주문/배송아이템 버튼 수정, 결제화면 작업 #6
  agijagi/app/src/main/res/drawable/order_call_20px.xml
  agijagi/app/src/main/res/drawable/order_chat_bubble_20px.xml
  agijagi/app/src/main/res/drawable/order_default_image.png
  agijagi/app/src/main/res/drawable/order_delivery_complete_off.png
  agijagi/app/src/main/res/drawable/order_delivery_complete_on.png
  agijagi/app/src/main/res/drawable/order_delivery_off.png
  agijagi/app/src/main/res/drawable/order_delivery_on.png
  agijagi/app/src/main/res/drawable/order_delivery_ready_off.png
  agijagi/app/src/main/res/drawable/order_delivery_ready_on.png
  agijagi/app/src/main/res/layout/fragment_order_detail.xml
  agijagi/app/src/main/res/layout/fragment_payment.xml
  agijagi/app/src/main/res/layout/item_order.xml
  agijagi/app/src/main/res/values/array.xml
Labels: Design

#26 Design: 사용자 커스텀 상품상세정보 화면 UI 수정 #10
  agijagi/app/src/main/res/drawable/custom_product_notice_box_rounded.xml
  agijagi/app/src/main/res/drawable/floating_button_background.xml
  agijagi/app/src/main/res/drawable/img.png
  agijagi/app/src/main/res/layout/activity_main.xml
  agijagi/app/src/main/res/layout/custom_floating_button.xml
  agijagi/app/src/main/res/layout/fragment_custom_product_detail.xml
Labels: Design

#28 Fix: navigation_graph 삭제로 생긴 오류 수정 #27
  agijagi/app/src/main/res/navigation/navigation_graph.xml
Labels: Fix

#29 Design: ShoppingList 화면 구현 #5
  agijagi/app/src/main/java/likelion/project/agijagi/shopping/ShoppingListAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/shopping/ShoppingListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/shopping/ShoppingListModel.kt
  agijagi/app/src/main/res/drawable/check_circle_20px.xml
  agijagi/app/src/main/res/drawable/line_12.xml
  agijagi/app/src/main/res/drawable/radio_button_unchecked_20px.xml
  agijagi/app/src/main/res/drawable/shopping_list_card_background.xml
  agijagi/app/src/main/res/drawable/shopping_list_circle_checkbox_selector.xml
  agijagi/app/src/main/res/drawable/shopping_list_no_item_logo.png
  agijagi/app/src/main/res/drawable/shopping_list_small_circle_checkbox_selector.xml
  agijagi/app/src/main/res/layout/fragment_shopping_list.xml
  agijagi/app/src/main/res/layout/item_shopping_list.xml
  agijagi/app/src/main/res/navigation/navigation_graph.xml
  agijagi/app/src/main/res/values/colors.xml
  agijagi/app/src/main/res/values/themes.xml
Labels: Design

#30 Design: 사용자 상품상세정보 화면, 판매자 상품상세정보 미리보기 화면 버튼 클릭 리스너 추가 #10
  agijagi/app/src/main/java/likelion/project/agijagi/product/CustomProductDetailFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/product/ProductDetailFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductDetailPreviewFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/SellerProductDetailFragment.kt
  agijagi/app/src/main/res/drawable/favorite_pressed_button.xml
  agijagi/app/src/main/res/layout/custom_floating_button.xml
  agijagi/app/src/main/res/layout/fragment_custom_option.xml
  agijagi/app/src/main/res/layout/fragment_custom_product_detail.xml
  agijagi/app/src/main/res/layout/fragment_product_detail.xml
  agijagi/app/src/main/res/layout/fragment_product_detail_preview.xml
  agijagi/app/src/main/res/layout/fragment_product_list.xml
  agijagi/app/src/main/res/layout/fragment_product_update.xml
  agijagi/app/src/main/res/layout/fragment_ready_made_option.xml
  agijagi/app/src/main/res/layout/fragment_seller_product_detail.xml
  agijagi/app/src/main/res/layout/fragment_user_chat_list.xml
  agijagi/app/src/main/res/navigation/navigation_graph.xml
Labels: Design

#32 Design: 화면별 바텀 네비게이션 유무 설정
  agijagi/app/src/main/java/likelion/project/agijagi/MainActivity.kt
Labels: Design

#34 [Design] 커스텀 플로팅 버튼 xml 수정 #10
  agijagi/app/src/main/res/layout/custom_floating_button.xml
Labels: Design

#35 Design: Order, purchase 화면 코드작업 #6
  agijagi/app/src/main/java/likelion/project/agijagi/order/OrderAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/order/OrderDetailFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/order/OrderFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/order/OrderModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/purchase/PaymentFragment.kt
  agijagi/app/src/main/res/layout/fragment_order.xml
  agijagi/app/src/main/res/layout/fragment_payment.xml
  agijagi/app/src/main/res/layout/item_order.xml
  agijagi/app/src/main/res/navigation/navigation_graph.xml
Labels: Design

#39 Design: order, purchase UI 수정 #6
  agijagi/app/src/main/java/likelion/project/agijagi/purchase/PaymentFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/purchase/PurchaseCompleteFragment.kt
  agijagi/app/src/main/res/layout/fragment_payment.xml
  agijagi/app/src/main/res/layout/fragment_purchase_complete.xml
  agijagi/app/src/main/res/navigation/navigation_graph.xml
Labels: Design

#45 Design: purchase, payment, deliveryTracking UI 수정 #6
  agijagi/app/src/main/java/likelion/project/agijagi/deliverytracking/DeliveryTrackingFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/order/OrderAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/order/OrderDetailFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/purchase/PaymentFragment.kt
  agijagi/app/src/main/res/layout/fragment_delivery_tracking.xml
  agijagi/app/src/main/res/layout/fragment_order_detail.xml
  agijagi/app/src/main/res/layout/fragment_payment.xml
  agijagi/app/src/main/res/navigation/navigation_graph.xml
Labels: Design

#51 Fix: favorite button 수정
  agijagi/app/src/main/java/likelion/project/agijagi/wishlist/WishListAdapter.kt
  agijagi/app/src/main/res/layout/item_wish_list.xml
Labels: Fix

#53 Design: SellerMyPage 구현
  agijagi/app/src/main/res/drawable/chat_24px.xml
  agijagi/app/src/main/res/drawable/line_1.xml
  agijagi/app/src/main/res/drawable/notifications_24px.xml
  agijagi/app/src/main/res/layout/fragment_seller_mypage.xml
  agijagi/app/src/main/res/menu/menu_seller_my_page.xml
Labels: Design

#54 Design: 검색 화면 뒤로가기 버튼 화면 연결 #33
  agijagi/app/build.gradle
  agijagi/app/src/main/java/likelion/project/agijagi/purchase/PaymentFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/search/SearchFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/search/SearchResultAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/search/SearchResultModel.kt
  agijagi/app/src/main/res/drawable/search_result_default_image.png
  agijagi/app/src/main/res/layout/fragment_search.xml
  agijagi/app/src/main/res/layout/item_search_search_result.xml
Labels: Design

#57 Feat: Splash 화면 구현
  agijagi/app/build.gradle
  agijagi/app/src/main/AndroidManifest.xml
  agijagi/app/src/main/ic_launcher-playstore.png
  agijagi/app/src/main/java/likelion/project/agijagi/MainActivity.kt
  agijagi/app/src/main/res/drawable/splash_logo2.png
  agijagi/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  agijagi/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  agijagi/app/src/main/res/mipmap-hdpi/ic_launcher.png
  agijagi/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  agijagi/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  agijagi/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  agijagi/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  agijagi/app/src/main/res/mipmap-mdpi/ic_launcher.png
  agijagi/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  agijagi/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  agijagi/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  agijagi/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  agijagi/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  agijagi/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  agijagi/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  agijagi/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  agijagi/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  agijagi/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  agijagi/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  agijagi/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  agijagi/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  agijagi/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  agijagi/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  agijagi/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  agijagi/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  agijagi/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  agijagi/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  agijagi/app/src/main/res/values/ic_launcher_background.xml
  agijagi/app/src/main/res/values/themes.xml
Labels: Feat

#58 Fix: 뒤로가기 버튼 추가 #5
  agijagi/app/src/main/java/likelion/project/agijagi/shopping/ShoppingListFragment.kt
  agijagi/app/src/main/res/layout/fragment_shopping_list.xml
Labels: Fix

#59 Feat: 저장할 데이터 유효성 검사, 갤러리 사진 추가 #48
  agijagi/app/src/main/AndroidManifest.xml
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductAddFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductAddModel.kt
  agijagi/app/src/main/res/drawable/agijagi_logo_vector_square.xml
  agijagi/app/src/main/res/layout/fragment_product_add.xml
  agijagi/app/src/main/res/layout/item_product_add_add_picture.xml
  agijagi/app/src/main/res/layout/item_product_add_add_plan.xml
Labels: Feat

#61 Design: 로그인, 회원가입, 카테고리 ui 구현 #2
  agijagi/app/src/main/java/likelion/project/agijagi/MainActivity.kt
  agijagi/app/src/main/java/likelion/project/agijagi/category/CategoryDetailInfoListAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/category/CategoryDetailInfoListFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/category/CategoryDetailInfoListModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/purchase/PaymentFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/signup/SignupSelectFragment.kt
  agijagi/app/src/main/res/layout/fragment_category_detail_info_list.xml
  agijagi/app/src/main/res/layout/fragment_home.xml
  agijagi/app/src/main/res/layout/item_category_detail_info_list.xml
Labels: Design

#65 Design: 배송관리 UI #43
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/ShippingManagementFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/adapter/ShippingManagementAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/buyermypage/model/ShippingManagementModel.kt
  agijagi/app/src/main/java/likelion/project/agijagi/purchase/PaymentFragment.kt
  agijagi/app/src/main/res/layout/fragment_shipping_add.xml
  agijagi/app/src/main/res/layout/fragment_shipping_management.xml
  agijagi/app/src/main/res/layout/item_shipping_management.xml
  agijagi/app/src/main/res/navigation/navigation_graph.xml
Labels: Design

#73 Design: 화면 연결 추가 #56
  agijagi/app/src/main/java/likelion/project/agijagi/MainActivity.kt
  agijagi/app/src/main/res/menu/menu_bottom_navigation_mainactivity.xml
  agijagi/app/src/main/res/navigation/navigation_graph.xml
Labels: Design

#76 Refactor: onCreateView 뷰 제어 코드 onViewCreated로 이동 #75
  agijagi/app/src/main/java/likelion/project/agijagi/product/CustomProductDetailFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/product/ProductDetailFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/search/SearchFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductDetailPreviewFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/SellerProductDetailFragment.kt
Labels: Refactor

#77 Refactor: 함수명 변경 #74
  agijagi/app/src/main/java/likelion/project/agijagi/category/CategoryFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/category/OrderMadeCategoryFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/home/HomeFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/product/CustomProductDetailFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/product/ProductDetailFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/ProductDetailPreviewFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/sellermypage/SellerProductDetailFragment.kt
Labels: Refactor

#80 Design: order UI 수정 #6
  agijagi/app/src/main/java/likelion/project/agijagi/deliverytracking/DeliveryTrackingFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/order/OrderAdapter.kt
  agijagi/app/src/main/java/likelion/project/agijagi/order/OrderFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/purchase/PaymentFragment.kt
  agijagi/app/src/main/java/likelion/project/agijagi/purchase/PurchaseCompleteFragment.kt
  agijagi/app/src/main/res/layout/item_order.xml
Labels: Design, Refactor
